"""Golden regression: ICP scoring is self-consistent against the reference operator.

The deterministic ICP inputs of ``workflows.quality_gate`` (keyword lists,
industry buckets, numeric weights, score bands, geography lists, disqualifier
families) are loaded from ``config/icp.yaml`` (here: the synthetic Acme operator
at ``examples/acme/config/icp.yaml``, via the conftest ``OUTBOUND_CONFIG_DIR``
pin) into ``ICPConfig``. The scoring MATH/LOGIC lives in code, not config.

BASELINE NOTE — the ``GOLDEN`` dict below was REGENERATED by running
``score_prospect`` over the fixture set under the synthetic Acme ICP. It is a
self-consistent regression guard on the scoring logic: a future change to the
scoring MATH (or to the Acme reference config) that shifts any score, band,
verdict-path, persona, lane, or breakdown component fails this test. It is NOT
the original post==pre-refactor equivalence proof — that proof ran against the
prior operator's real values and was retired with that data when the repo was
prepared for public release (see examples/acme/README.md).

Fixtures span the whole score space: decision-makers, the ops-in-industrial
joint case, off-ICP industries, sales-role + junior-IC hard disqualifiers,
company-keyed disqualifiers (PE, state-owned) and title-keyed ones
(HR/Finance/Innovation), academics, consultants, competitors, the global-exec
demote + its in-region override, all three scoring lanes (legacy / enterprise /
target_company), the low-confidence industry abstain, the S&OP exemption, the
ERP signal, unknown/blank inputs, and borderline-band fallback.
"""

from workflows.icp_config import ICPConfig, load_icp_config
from workflows.quality_gate import score_band, score_prospect


def _pc(mode=None, key=None):
    d = {}
    if mode == "tc":
        d["target_company_mode"] = True
    elif mode == "en":
        d["enterprise_mode"] = True
    if key:
        d["key"] = key
    return d or None


# (id, prospect_data, persona_config). Neutral, fabricated prospects spanning
# the score space under the Acme reference ICP.
FIXTURES = [
    ("dm_inicp_enterprise", {"title": "VP Operations", "company": "Globex", "location": "United States", "employee_count": 8000, "industry": "Manufacturing"}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("ops_joint_inicp", {"title": "Production Manager", "company": "Initech", "location": "Canada", "employee_count": 6000, "industry": "Logistics"}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("ops_officp", {"title": "Operations Manager", "company": "Hooli", "location": "United Kingdom", "employee_count": 3000, "industry": "Other"}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("sales_role_dq", {"title": "VP Sales", "company": "Stark Industrial", "location": "United States", "employee_count": 5000, "industry": "Manufacturing"}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("junior_ic", {"title": "Production Coordinator", "company": "Wayne Manufacturing", "location": "United States", "employee_count": 7000, "industry": "Manufacturing"}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("pe_firm", {"title": "Operating Partner", "company": "Vehement Private Equity Fund", "location": "United States", "employee_count": 500, "industry": "Other"}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("academic", {"title": "Professor of Engineering", "company": "Riverside University", "location": "United States", "employee_count": 5000, "industry": "Other"}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("consultant", {"title": "Supply Chain Consultant", "company": "Advisory Group", "location": "United States", "employee_count": 9000, "industry": "Other"}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("state_owned", {"title": "Director of Operations", "company": "Ministry of Industry", "location": "United States", "employee_count": 100000, "industry": "Manufacturing"}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("global_with_override", {"title": "VP Global Operations Mexico", "company": "Soylent Foods", "location": "Mexico City, Mexico", "employee_count": 10000, "industry": "Manufacturing"}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("global_only", {"title": "Global Head of Manufacturing", "company": "Soylent Foods", "location": "Germany", "employee_count": 10000, "industry": "Manufacturing"}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("competitor", {"title": "Solutions Director", "company": "Competitor Inc", "location": "United States", "employee_count": 5000, "industry": "Other"}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("hr_dq", {"title": "Human Resources Director", "company": "Cyberdyne Systems", "location": "United States", "employee_count": 8000, "industry": "Manufacturing"}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("finance_dq", {"title": "CFO", "company": "Tyrell Manufacturing", "location": "United States", "employee_count": 12000, "industry": "Financial Services"}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("innovation_dq", {"title": "Head of R&D", "company": "Massive Dynamic", "location": "United States", "employee_count": 4000, "industry": "Healthcare"}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("midmarket_sweet", {"title": "General Manager", "company": "Vandelay Industries", "location": "United States", "employee_count": 800, "industry": "Manufacturing"}, {"target_company_mode": True, "key": "operations_leaders", "search_size_credit": 15}),
    ("midmarket_unknown", {"title": "Director of Operations", "company": "Pied Piper", "location": "Canada", "employee_count": None, "industry": "Logistics"}, {"target_company_mode": True, "key": "operations_leaders", "search_size_credit": 15}),
    ("legacy_small_lowrole", {"title": "Warehouse Worker", "company": "SmallCo", "location": "Australia", "employee_count": 50, "industry": None}, None),
    ("legacy_large_dm", {"title": "Managing Director", "company": "BigCorp", "location": "Australia", "employee_count": 5000, "industry": None}, None),
    ("blank", {"title": "", "company": "", "location": "", "employee_count": None, "industry": None}, None),
    ("digi_champion", {"title": "Director of Digital Transformation", "company": "Encom Manufacturing", "location": "United States", "employee_count": 9000, "industry": "Technology"}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("lowconf_industry", {"title": "Operations Director", "company": "Rand Logistics", "location": "United States", "employee_count": 6000, "industry": "Manufacturing", "industry_vertical_status": "low_confidence"}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("ops_domain_only", {"title": "Supply Chain Manager", "company": "AutoCorp", "location": "United States", "employee_count": 5000, "industry": "Retail"}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("snop_exempt", {"title": "S&OP Director", "company": "Bishop Industrial", "location": "Brazil", "employee_count": 4000, "industry": "Healthcare"}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("erp_small_sub", {"title": "COO", "company": "SubCo", "location": "Chile", "employee_count": 300, "industry": "Manufacturing", "company_headline": "Running SAP S/4HANA", "description": ""}, {"enterprise_mode": True, "search_size_credit": 15}),
    ("borderline_nollm", {"title": "Quality Lead", "company": "PackCo", "location": "United States", "employee_count": 2000, "industry": "Retail"}, {"enterprise_mode": True, "search_size_credit": 15}),
]

# Regenerated golden values — captured by running score_prospect over FIXTURES
# under the Acme reference ICP. Self-consistent regression baseline (see module
# docstring); regenerate deliberately only when the scoring logic is changed.
GOLDEN = {
    'dm_inicp_enterprise': {'score': 75, 'band': '60-75', 'verdict_path': 'borderline_pass', 'pass': True, 'persona': 'executive_sponsors', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'role': 28, 'competitor': 20, 'industry': 12, 'ops_in_industrial': 0, 'total': 75, 'scale_version': '2026-07-search-credit'}},
    'ops_joint_inicp': {'score': 65, 'band': '60-75', 'verdict_path': 'borderline_pass', 'pass': True, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'competitor': 20, 'role': 0, 'industry': 0, 'ops_in_industrial': 30, 'total': 65, 'scale_version': '2026-07-search-credit'}},
    'ops_officp': {'score': 34, 'band': '<40', 'verdict_path': 'deterministic_reject', 'pass': False, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'role': 24, 'competitor': 20, 'industry': -25, 'ops_in_industrial': 0, 'total': 34, 'scale_version': '2026-07-search-credit'}},
    'sales_role_dq': {'score': 35, 'band': '<40', 'verdict_path': 'deterministic_reject_sales_role', 'pass': False, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'role': 28, 'competitor': 20, 'sales_role_penalty': -40, 'industry': 12, 'ops_in_industrial': 0, 'total': 35, 'scale_version': '2026-07-search-credit'}},
    'junior_ic': {'score': 19, 'band': '<40', 'verdict_path': 'deterministic_reject_junior_ic', 'pass': False, 'persona': 'executive_sponsors', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'role': 12, 'competitor': 20, 'junior_ic_penalty': -40, 'industry': 12, 'ops_in_industrial': 0, 'total': 19, 'scale_version': '2026-07-search-credit'}},
    'pe_firm': {'score': 12, 'band': '<40', 'verdict_path': 'disqualifier_pe', 'pass': False, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'role': 2, 'competitor': 20, 'industry': -25, 'ops_in_industrial': 0, 'total': 12, 'scale_version': '2026-07-search-credit'}},
    'academic': {'score': 0, 'band': '<40', 'verdict_path': 'disqualifier_academic', 'pass': False, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'role': 2, 'competitor': 5, 'industry': -25, 'ops_in_industrial': 0, 'total': 0, 'scale_version': '2026-07-search-credit'}},
    'consultant': {'score': 10, 'band': '<40', 'verdict_path': 'disqualifier_consulting', 'pass': False, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'role': 12, 'competitor': 8, 'industry': -25, 'ops_in_industrial': 0, 'total': 10, 'scale_version': '2026-07-search-credit'}},
    'state_owned': {'score': 75, 'band': '60-75', 'verdict_path': 'disqualifier_state_owned', 'pass': False, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'role': 28, 'competitor': 20, 'industry': 12, 'ops_in_industrial': 0, 'total': 75, 'scale_version': '2026-07-search-credit'}},
    'global_with_override': {'score': 75, 'band': '60-75', 'verdict_path': 'borderline_pass', 'pass': True, 'persona': 'executive_sponsors', 'language': 'es', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'role': 28, 'competitor': 20, 'industry': 12, 'ops_in_industrial': 0, 'total': 75, 'scale_version': '2026-07-search-credit'}},
    'global_only': {'score': 49, 'band': '40-59', 'verdict_path': 'borderline_reject', 'pass': False, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'role': 2, 'competitor': 20, 'industry': 12, 'ops_in_industrial': 0, 'total': 49, 'scale_version': '2026-07-search-credit'}},
    'competitor': {'score': 18, 'band': '<40', 'verdict_path': 'disqualifier_competitor', 'pass': False, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'role': 28, 'competitor': 0, 'industry': -25, 'ops_in_industrial': 0, 'total': 18, 'scale_version': '2026-07-search-credit'}},
    'hr_dq': {'score': 75, 'band': '60-75', 'verdict_path': 'disqualifier_hr', 'pass': False, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'role': 28, 'competitor': 20, 'industry': 12, 'ops_in_industrial': 0, 'total': 75, 'scale_version': '2026-07-search-credit'}},
    'finance_dq': {'score': 75, 'band': '60-75', 'verdict_path': 'disqualifier_finance', 'pass': False, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'role': 28, 'competitor': 20, 'industry': 12, 'ops_in_industrial': 0, 'total': 75, 'scale_version': '2026-07-search-credit'}},
    'innovation_dq': {'score': 75, 'band': '60-75', 'verdict_path': 'disqualifier_innovation', 'pass': False, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'role': 28, 'competitor': 20, 'industry': 12, 'ops_in_industrial': 0, 'total': 75, 'scale_version': '2026-07-search-credit'}},
    'midmarket_sweet': {'score': 75, 'band': '60-75', 'verdict_path': 'borderline_pass', 'pass': True, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'target_company_mode', 'breakdown': {'size': 15, 'role': 28, 'competitor': 20, 'industry': 12, 'ops_in_industrial': 0, 'total': 75, 'scale_version': '2026-07-search-credit'}},
    'midmarket_unknown': {'score': 75, 'band': '60-75', 'verdict_path': 'borderline_pass', 'pass': True, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'target_company_mode', 'breakdown': {'size': 15, 'role': 28, 'competitor': 20, 'industry': 12, 'ops_in_industrial': 0, 'total': 75, 'scale_version': '2026-07-search-credit'}},
    'legacy_small_lowrole': {'score': 22, 'band': '<40', 'verdict_path': 'deterministic_reject', 'pass': False, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'legacy', 'breakdown': {'size': 0, 'role': 2, 'competitor': 20, 'industry': 0, 'ops_in_industrial': 0, 'total': 22, 'scale_version': '2026-07-search-credit'}},
    'legacy_large_dm': {'score': 48, 'band': '40-59', 'verdict_path': 'borderline_reject', 'pass': False, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'legacy', 'breakdown': {'size': 0, 'role': 28, 'competitor': 20, 'industry': 0, 'ops_in_industrial': 0, 'total': 48, 'scale_version': '2026-07-search-credit'}},
    'blank': {'score': 22, 'band': '<40', 'verdict_path': 'deterministic_reject', 'pass': False, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'legacy', 'breakdown': {'size': 0, 'role': 2, 'competitor': 20, 'industry': 0, 'ops_in_industrial': 0, 'total': 22, 'scale_version': '2026-07-search-credit'}},
    'digi_champion': {'score': 75, 'band': '60-75', 'verdict_path': 'borderline_pass', 'pass': True, 'persona': 'digitalization_champions', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'role': 28, 'competitor': 20, 'industry': 12, 'ops_in_industrial': 0, 'total': 75, 'scale_version': '2026-07-search-credit'}},
    'lowconf_industry': {'score': 63, 'band': '60-75', 'verdict_path': 'borderline_pass', 'pass': True, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'role': 28, 'competitor': 20, 'industry': 0, 'ops_in_industrial': 0, 'total': 63, 'scale_version': '2026-07-search-credit'}},
    'ops_domain_only': {'score': 65, 'band': '60-75', 'verdict_path': 'borderline_pass', 'pass': True, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'competitor': 20, 'role': 0, 'industry': 0, 'ops_in_industrial': 30, 'total': 65, 'scale_version': '2026-07-search-credit'}},
    'snop_exempt': {'score': 75, 'band': '60-75', 'verdict_path': 'borderline_pass', 'pass': True, 'persona': 'operations_leaders', 'language': 'pt', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'role': 28, 'competitor': 20, 'industry': 12, 'ops_in_industrial': 0, 'total': 75, 'scale_version': '2026-07-search-credit'}},
    'erp_small_sub': {'score': 75, 'band': '60-75', 'verdict_path': 'borderline_pass', 'pass': True, 'persona': 'operations_leaders', 'language': 'es', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'role': 28, 'competitor': 20, 'industry': 12, 'ops_in_industrial': 0, 'total': 75, 'scale_version': '2026-07-search-credit'}},
    'borderline_nollm': {'score': 65, 'band': '60-75', 'verdict_path': 'borderline_pass', 'pass': True, 'persona': 'operations_leaders', 'language': 'en', 'icp_lane': None, 'scoring_lane': 'enterprise_mode', 'breakdown': {'size': 15, 'role': 18, 'competitor': 20, 'industry': 12, 'ops_in_industrial': 0, 'total': 65, 'scale_version': '2026-07-search-credit'}},
}


def _fixtures_by_id():
    return {fid: (pdata, pcfg) for fid, pdata, pcfg in FIXTURES}


def test_fixture_count_matches_golden():
    """Every fixture has a golden entry and vice versa (no silent drop)."""
    assert {fid for fid, _, _ in FIXTURES} == set(GOLDEN)
    assert len(FIXTURES) == 26


def test_score_prospect_matches_golden():
    """score_prospect output matches the regenerated golden for every fixture.

    Asserts an EXACT match on score, band, verdict_path, pass, persona,
    language, icp_lane, scoring_lane, and the full component breakdown for
    every fixture. A 1-point drift or verdict change fails here.
    """
    by_id = _fixtures_by_id()
    mismatches = []
    for fid, expected in GOLDEN.items():
        pdata, pcfg = by_id[fid]
        r = score_prospect(pdata, pcfg)
        actual = {
            "score": r["score"],
            "band": score_band(r["score"]),
            "verdict_path": r["verdict_path"],
            "pass": r["pass"],
            "persona": r["persona"],
            "language": r["language"],
            "icp_lane": r.get("icp_lane"),
            "scoring_lane": r["scoring_lane"],
            "breakdown": {k: v for k, v in r["score_breakdown"].items() if k != "reasons"},
        }
        if actual != expected:
            mismatches.append((fid, expected, actual))
    assert not mismatches, "Scoring drift vs the regenerated golden:\n" + "\n".join(
        f"  {fid}:\n    expected={exp}\n    actual  ={act}" for fid, exp, act in mismatches
    )


def test_load_icp_config_returns_acme_reference():
    """The conftest OUTBOUND_CONFIG_DIR pin loads the synthetic Acme reference ICP
    from examples/acme/config/icp.yaml (which mirrors the shipped neutral
    config/icp.example.yaml; see
    test_shipped_neutral_icp_example_is_loadable_and_neutral)."""
    cfg = load_icp_config()
    assert isinstance(cfg, ICPConfig)
    # Spot-check one of each type fed the scorer.
    assert cfg.industry_bonus_in_icp == 12
    assert cfg.industry_penalty_off_icp == -25
    assert cfg.ops_in_industrial_combined == 30
    assert cfg.score_band_labels == ("<40", "40-59", "60-75", ">75")
    assert "Manufacturing" in cfg.in_icp_industries
    assert cfg.off_icp_industries == frozenset({"Other"})
    # Disqualifier-family order is load-bearing (earliest positional match).
    assert cfg.pe_keywords[0] == "private equity fund"
    assert "government of" in cfg.state_owned_keywords
    # Consulting families (sixth disqualifier) are loaded as required lists.
    assert "accenture" in cfg.consulting_firm_keywords
    assert "consultant" in cfg.consulting_title_keywords


def test_quality_gate_constants_sourced_from_config():
    """Module-level names in quality_gate are populated from the loaded config."""
    import workflows.quality_gate as qg

    cfg = load_icp_config()
    assert cfg.industry_bonus_in_icp == qg.INDUSTRY_BONUS_IN_ICP
    assert cfg.decision_maker_keywords == qg.DECISION_MAKER_KEYWORDS
    assert cfg.in_icp_industries == qg.IN_ICP_INDUSTRIES
    assert cfg.ops_override_keywords == qg.OPS_OVERRIDE_KEYWORDS
    assert cfg.score_band_labels == qg.SCORE_BAND_LABELS


def test_shipped_neutral_icp_example_is_loadable_and_neutral(tmp_path, monkeypatch):
    """The SHIPPED repo-root config/icp.example.yaml stays schema-valid AND neutral.

    The whole suite resolves the Acme reference ICP via the conftest
    OUTBOUND_CONFIG_DIR pin (examples/acme/config), so the public default at
    repo-root config/ is never
    otherwise exercised. Without this guard, a malformed or un-scrubbed shipped
    default would go unnoticed — the conftest pin would mask it. We copy the real
    shipped example into an isolated dir (as icp.example.yaml, so a developer's
    local config/icp.yaml can't shadow it) and assert it loads fully and carries
    no original-operator ICP identifiers.
    """
    import shutil
    from pathlib import Path

    from workflows import icp_config as _icp_mod

    repo_root = Path(_icp_mod.__file__).resolve().parent.parent
    shipped = repo_root / "config" / "icp.example.yaml"

    cfg_dir = tmp_path / "config"
    cfg_dir.mkdir()
    shutil.copy(shipped, cfg_dir / "icp.example.yaml")
    monkeypatch.setenv("OUTBOUND_CONFIG_DIR", str(cfg_dir))

    cfg = load_icp_config()
    assert isinstance(cfg, ICPConfig)

    # Schema completeness — a representative field from each section is present.
    assert cfg.score_band_labels == ("<40", "40-59", "60-75", ">75")
    assert cfg.off_icp_industries == frozenset({"Other"})
    assert cfg.in_icp_industries  # non-empty in-ICP bucket
    assert len(cfg.qualifier_lane_labels) == 2
    assert cfg.qualifier_product_summary and cfg.qualifier_geography_requirement
    assert cfg.qualifier_lanes and cfg.qualifier_disqualifiers
    # Every required keyword family is a list (loader already validates types).
    assert isinstance(cfg.decision_maker_keywords, list)
    assert isinstance(cfg.sales_role_keywords, list)

    # Neutrality — none of the reference operator's ICP identifiers leak into the
    # public default. Scan the narrative qualifier slots AND the named-entity
    # disqualifier families (competitor / PE / state-owned), where the original
    # operator's concrete company names lived — so a future edit pasting one of those
    # back into the neutral template is caught, not just the prose slots. (The
    # geography/language-detection lists legitimately name real markets like
    # Mexico/Brazil for ANY Spanish/Portuguese sender, so they are NOT scanned.)
    blob = " ".join(
        [
            cfg.qualifier_product_summary,
            cfg.qualifier_geography_requirement,
            *cfg.qualifier_lanes,
            *cfg.qualifier_disqualifiers,
            *cfg.qualifier_lane_labels,
            *cfg.competitor_keywords,
            *cfg.pe_keywords,
            *cfg.state_owned_keywords,
        ]
    ).lower()
    for needle in (
        "lucie",
        "latam",
        "$500m",
        "production scheduling",
        "pemex",
        "petrobras",
        "codelco",
        "siemens",
        "opcenter",
        "advent international",
        "kkr",
    ):
        assert needle not in blob, (
            f"{needle!r} leaked into the shipped neutral config/icp.example.yaml default"
        )
