"""Structural tests for the slash-command registry."""

from __future__ import annotations

from pathlib import Path

import pytest
from click.testing import CliRunner

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO_ROOT / "skills"

# The 7 operational slash commands the registry must define. Each maps to a
# cli.py subcommand, touches Attio data (so requires the step-0 MCP canary), and
# must have a corresponding SKILL.md.
EXPECTED_SKILLS: frozenset[str] = frozenset({
    "sales-daily",
    "sales-weekly",
    "health-check",
    "sales-finalize-borderline",
    "data-quality-report",
    "threshold-calibration",
    "audit-reminder-sweep",
})

# Install-time / orchestration skills that are NOT operational slash commands:
# they have no cli.py subcommand and touch no Attio data, so the canary +
# cli-reference + extra-dir contracts below do not apply to them. `onboard`
# (the install-time CRM/PhantomBuster/ICP onboarding agent) is one — it is an
# interview-and-orchestrate procedure, not an Attio-data command.
NON_COMMAND_SKILLS: frozenset[str] = frozenset({
    "onboard",
})


class TestSkillsDirectory:
    def test_skills_dir_exists(self):
        assert SKILLS_DIR.is_dir(), f"skills/ must exist at {SKILLS_DIR}"

    def test_all_seven_skills_present(self):
        actual = {
            p.name for p in SKILLS_DIR.iterdir() if p.is_dir()
        }
        missing = EXPECTED_SKILLS - actual
        # Extra dirs are allowed only if they are declared non-command skills
        # (install-time/orchestration, e.g. `onboard`). Anything else is an
        # unregistered operational slash command and fails.
        extra = actual - EXPECTED_SKILLS - NON_COMMAND_SKILLS
        assert not missing, f"missing skill dirs: {missing}"
        assert not extra, f"unexpected skill dirs: {extra}"

    @pytest.mark.parametrize(
        "skill_name", sorted(EXPECTED_SKILLS | NON_COMMAND_SKILLS)
    )
    def test_skill_has_skill_md(self, skill_name: str):
        skill_md = SKILLS_DIR / skill_name / "SKILL.md"
        assert skill_md.is_file(), f"{skill_md} missing"
        text = skill_md.read_text(encoding="utf-8")
        # YAML frontmatter must declare the matching name + a description.
        assert text.startswith("---"), f"{skill_md} missing YAML frontmatter"
        assert f"name: {skill_name}" in text
        assert "description:" in text


class TestNoCronInstall:
    """No cron, no launchd. The cron install scripts must be gone,
    AND no future shell script under scripts/ may carry `cron` in
    its name.

    Scope is tracked files (``git ls-files``), not the developer's
    on-disk working tree. The contract here is "main/the merge commit
    must not contain a cron script" — an untracked stale install-cron.sh
    in a dev's worktree (left behind from the 2026-05-21 cron deletion,
    or auto-generated by a different branch) is not a repo regression
    and should not fail this guard.
    """

    @staticmethod
    def _tracked_files() -> frozenset[str]:
        import subprocess
        out = subprocess.run(
            ["git", "ls-files"],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
        return frozenset(line.strip() for line in out.stdout.splitlines() if line.strip())

    @pytest.mark.parametrize("relpath", [
        "scripts/install-cron.sh",
        "scripts/daily-cron.sh",
        "scripts/weekly-learn.sh",
    ])
    def test_legacy_cron_script_removed(self, relpath: str):
        tracked = self._tracked_files()
        assert relpath not in tracked, (
            f"{relpath} is tracked in git — slash commands replace cron, "
            f"this script must be removed via `git rm`."
        )

    def test_no_new_cron_scripts_under_scripts(self):
        """Glob-wide guard so a future `scripts/monthly-cron.sh` or
        similar can't slip in without tripping the registry test.

        Checks tracked files only (same rationale as
        test_legacy_cron_script_removed)."""
        tracked = self._tracked_files()
        offenders = sorted(
            f for f in tracked
            if f.startswith("scripts/") and "cron" in f.rsplit("/", 1)[-1]
        )
        assert not offenders, (
            f"shell scripts whose names contain 'cron' are forbidden: "
            f"{offenders}"
        )

    def test_install_skills_script_present(self):
        assert (REPO_ROOT / "scripts/install-skills.sh").is_file()


class TestMcpCanaryStepZero:
    """Every slash command that touches Attio data MUST include the
    MCP scope canary as step 0. Without this, a stale token would
    silently produce empty queries and the operator would see "OK"
    when the read never landed.

    `health-check` is exempt — it IS the connectivity probe, and
    the exemption is documented explicitly in its SKILL.md.
    """

    SKILLS_REQUIRING_CANARY = sorted(EXPECTED_SKILLS - {"health-check"})

    @pytest.mark.parametrize("skill_name", SKILLS_REQUIRING_CANARY)
    def test_skill_has_step_0_canary(self, skill_name: str):
        text = (SKILLS_DIR / skill_name / "SKILL.md").read_text(encoding="utf-8")
        assert "Step 0 — Verify Attio MCP scope" in text, (
            f"skills/{skill_name}/SKILL.md missing step-0 canary heading"
        )


class TestNewCliSubcommands:
    """Each slash command must have a matching Python entry point in
    cli.py so the SKILL.md can invoke it."""

    @pytest.mark.parametrize("subcommand", [
        "data-quality-report",
        "threshold-calibration",
        "audit-reminder-sweep",
        "health-check",
        "sales-finalize-borderline",
    ])
    def test_subcommand_registered(self, subcommand: str):
        from cli import cli

        # `cli.commands` is the Click registry of subcommands.
        assert subcommand in cli.commands, (
            f"sales {subcommand} not registered in cli.py"
        )

    def test_data_quality_report_help_runs(self):
        from cli import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["data-quality-report", "--help"])
        assert result.exit_code == 0
        assert "--period-days" in result.output
        assert "--no-write" in result.output

    def test_threshold_calibration_help_runs(self):
        from cli import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["threshold-calibration", "--help"])
        assert result.exit_code == 0
        assert "--dry-run" in result.output

    def test_audit_reminder_sweep_help_runs(self):
        from cli import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["audit-reminder-sweep", "--help"])
        assert result.exit_code == 0
        assert "--stale-days" in result.output

    def test_health_check_help_runs(self):
        from cli import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["health-check", "--help"])
        assert result.exit_code == 0

    def test_sales_finalize_borderline_help_runs(self):
        from cli import cli

        runner = CliRunner()
        result = runner.invoke(cli, ["sales-finalize-borderline", "--help"])
        assert result.exit_code == 0
        assert "--batch" in result.output


class TestSkillMentionsExpectedCommand:
    """Smoke check: each SKILL.md mentions the cli subcommand it wraps.
    Cheap textual sanity — catches a SKILL that drifted from its
    Python entry point."""

    SKILL_TO_CLI: dict[str, str] = {
        "sales-daily": "sales daily",
        "sales-weekly": "sales weekly",
        "health-check": "sales health-check",
        "sales-finalize-borderline": "sales sales-finalize-borderline",
        "data-quality-report": "sales data-quality-report",
        "threshold-calibration": "sales threshold-calibration",
        "audit-reminder-sweep": "sales audit-reminder-sweep",
    }

    @pytest.mark.parametrize(
        "skill_name,expected_cli",
        sorted(SKILL_TO_CLI.items()),
    )
    def test_skill_references_its_cli_command(
        self, skill_name: str, expected_cli: str,
    ):
        text = (SKILLS_DIR / skill_name / "SKILL.md").read_text(encoding="utf-8")
        assert expected_cli in text, (
            f"skills/{skill_name}/SKILL.md must mention `{expected_cli}`"
        )
